MODEL_NAME = "claude-opus-4-7"
GEMINI_MODEL_NAME = "gemini-2.5-flash"
OPENAI_MODEL_NAME = "gpt-4o"
GENERATED_CODE_PATH = "generated/generated_code.py"
TRAIN_SUITE_PATH = "test_suite/train.json"   # the ONLY suite the reflection/fix loop may see
TEST_SUITE_PATH = "test_suite/test.json"     # held-out: evaluated once per run, final metric
PROMPT_PATH = "prompt.txt"
STATUTORY_TEXT_PATH = "statutory_text/grestg_paragraph1_abs3.txt"
RESULTS_DIR = "results/"
